name: macrolife
description: "A new Flutter project."
# publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
    sdk: ^3.5.3

dependencies:
    avatar_stack: ^1.2.0
    cached_network_image: ^3.4.1
    camera: ^0.11.0+2
    dotted_border: ^2.1.0
    dropdown_search: ^6.0.1
    flutter:
        sdk: flutter
    flutter_localization: ^0.2.2
    flutter_svg: ^2.0.10+1
    font_awesome_flutter: ^10.7.0
    get: ^4.6.6
    get_storage: ^2.1.1
    google_ml_kit: ^0.19.0
    http: ^1.2.2
    image: ^4.3.0
    image_picker: ^1.1.2
    package_info_plus: ^8.0.2
    percent_indicator: ^4.2.3
    syncfusion_flutter_charts: ^27.2.2
    syncfusion_flutter_gauges: ^27.2.4
    url_launcher: ^6.3.0
    flutter_native_splash: ^2.4.4
    flutter_paypal: ^0.2.1
    # razorpay_flutter: ^1.3.5
    # flutter_pay: ^1.0.1
    flutter_stripe: ^10.2.0
    pay: ^2.0.0
    dio: ^5.7.0
    sqflite: ^2.2.0
    shared_preferences: ^2.3.3
    flutter_xlider: ^3.5.0

    in_app_review: ^2.0.10
    # flutter_vibrate: ^1.0.0
    firebase_auth: ^5.3.4
    firebase_core: ^3.9.0
    sign_in_with_apple: ^6.1.4
    google_sign_in: ^6.2.2
    firebase_messaging: ^15.1.6
    video_player: ^2.9.2
    health: ^9.0.0
    # rflutter_alert: ^2.0.4
    carousel_slider: ^5.0.0
    home_widget: ^0.7.0
    share_plus: ^10.1.3
    fl_chart: ^0.70.0
    gif_view: ^1.0.0
    animated_weight_picker: ^1.0.3
    flutter_round_slider: ^1.0.0
    flutter_local_notifications: ^18.0.1
    workmanager: ^0.5.2




dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0
    flutter_launcher_icons: ^0.14.2

flutter_icons:
    android: true
    ios: true
    image_path: "assets/icons/icono_Macro_Life_1024x1024_favicon_negro.jpg"

flutter_native_splash:
  android: true
  ios: true
  color: "#ffffff" # Background color of the splash screen
  image: "assets/icons/logo_macrolife_vertical_negro_730x315_nuevo_1.png" # Path to your splash screen image


# flutter_native_splash:
#     color: "#ffffff"
#     image: assets/images/splash.png
#     android: true
#     ios: true
#     web: false
#     fullscreen: true

flutter:
    uses-material-design: true

    assets:
        - assets/icons/
        - assets/images/
        - assets/avatars/
        - assets/videos/
        - assets/gifs/

        # - assets/modulos/

    fonts:
        - family: InterTight
          fonts:
              - asset: assets/fonts/InterTight-Black.ttf
              - asset: assets/fonts/InterTight-BlackItalic.ttf
              - asset: assets/fonts/InterTight-Bold.ttf
              - asset: assets/fonts/InterTight-BoldItalic.ttf
              - asset: assets/fonts/InterTight-ExtraBold.ttf
              - asset: assets/fonts/InterTight-ExtraLight.ttf
              - asset: assets/fonts/InterTight-ExtraLightItalic.ttf
              - asset: assets/fonts/InterTight-Italic-VariableFont_wght.ttf
              - asset: assets/fonts/InterTight-Italic.ttf
              - asset: assets/fonts/InterTight-Light.ttf
              - asset: assets/fonts/InterTight-LightItalic.ttf
              - asset: assets/fonts/InterTight-Medium.ttf
              - asset: assets/fonts/InterTight-MediumItalic.ttf
              - asset: assets/fonts/InterTight-Regular.ttf
              - asset: assets/fonts/InterTight-SemiBold.ttf
              - asset: assets/fonts/InterTight-SemiBoldItalic.ttf
              - asset: assets/fonts/InterTight-Thin.ttf
              - asset: assets/fonts/InterTight-ThinItalic.ttf
              - asset: assets/fonts/InterTight-VariableFont_wght.ttf
                
                
                
                
